language: php
php:
  - '8.1'

services:
  - postgresql





before_script:
  - cp config/database.yml.travis config/package/doctrine.yaml
  - composer install
  - yarn install
  - yarn encore dev

script:
  - vendor/bin/phpunit
