language: php
php:
  - '8.1'

services:
  - postgresql

env:
  global:
    - DATABASE_URL="postgresql://postgres:395593@127.0.0.1:5432/ToDo?serverVersion=15&charset=utf8"


before_script:
  - composer install
  - yarn install
  - yarn encore dev

script:
  - vendor/bin/phpunit
