language: php
php:
  - '8.1'

services:
  - postgresql

before_script:
  - composer install
  - yarn install
  - yarn encore dev
  - psql -c 'create database ToDo_test;' -U postgres
  - php bin/console doctrine:schema:update --force

script:
  - php bin/console doctrine:fixtures:load
  - php bin/console tasks:anonymous
  - vendor/bin/phpunit
