language: php
php:
  - '8.1'

services:
  - postgresql

before_script:
  - composer install
  - yarn install
  - yarn encore dev
  - psql -c 'create database ToDo_test;' -U postgres -d postgres
  - psql -c 'create database ToDo;' -U postgres -d postgres
  - php bin/console doctrine:schema:update --env=test
  - php bin/console doctrine:schema:update --force




script:
  - php bin/console task:anonymous
  - php bin/console task:anonymous --env=test
  - vendor/bin/phpunit
