language: php
php:
  - '8.1'

services:
  - postgresql

before_script:
  - psql -c 'create database ToDo;' -U postgres

script:
  - composer install
  - yarn install
  - yarn encore dev
  - vendor/bin/phpunit
