language: php
php:
  - '8.1'

services:
  - postgresql

before_script:
  - php bin/console doctrine:database:create


script:
  - composer install
  - yarn install
  - yarn encore dev
  - vendor/bin/phpunit
