language: php
php:
  - '8.1'

services:
  - postgresql

before_script:
  - composer install
  - yarn install
  - yarn encore dev
  - psql -c 'create database todo_test;' -U postgres
  - DATABASE_URL=postgresql://postgres@localhost:5432/ToDo_test php bin/console d:s:u --force





script:
  - php bin/console d:f:l
  - php bin/console task:anonymous
  - vendor/bin/phpunit
